server:
  port: 8787
  servlet:
    context-path: /
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.5.50:8880
  messages:
    baseFolder: src/main/resources/i18n
    basename: ${spring.application.name}-message
    encoding: UTF-8
    cacheMillis: 1000
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000

# 连接超时时间，默认为1秒，该值会被FeignClient配置connectTimeout覆盖
ribbon:
  ConnectTimeout: 10000
  # 读超时时间，默认为1秒，该值会被FeignClient配置readTimeout覆盖
  ReadTimeout: 30000
  # 最大重试次数
  MaxAutoRetries: 3